### ISSUE TITLE
Would it be possible to provide a setup example?

### ISSUE THREAD

**Issue by RancidMilkGames** [tcmug/godot_trailmesh#1]
Hi, I thought the plugin looked neat and am trying to get it working in a project.

#### This is my guess as to what the scene structure should look like:
![image](https://github.com/tcmug/godot_trailmesh/assets/115530728/9d320537-13dd-4839-8933-0194030f494d)

#### Then I've tried lots of combos for the exposed inspector properties:
![image](https://github.com/tcmug/godot_trailmesh/assets/115530728/ed2a47fa-2448-4143-8d07-a221f1ccfb3c)

I'm guessing the curve and gradient can both be whatever, but I want to confirm that the geometry node path should point to the mesh and not the physics body? I've tried both to no avail. Then there's the material. Do I need a `ShaderMaterial` of some sort? I've tried several variations of the `StandardMaterial3D`, like with vertex color and/or particle trails enabled.

Thanks for making the plugin!

### Godot Version
v4.2.dev5.official [e3e2528ba]

**Comment by drewgonzales360** [comment]
I just tried this out and learned that you have to set the `GeometryNodePath` needs to be the world environment or some root node. The emitter leaves a trail relative to the world. I'll open a PR with documentation and an example

**Comment by RancidMilkGames** [comment]
@drewgonzales360 Changing the `GeometryNodePath` to the root scene made it work. Thanks!

**Comment by drewgonzales360** [comment]
Awesome! Glad it worked out for you. I wrote [this PR](https://github.com/tcmug/godot_trailmesh/pull/2) so that others can figure it out too.

**Comment by tcmug** [comment]
Would you think it makes sense to default to adding the mesh below the emitter itself when the geometry node path is not defined? 

The reason behind the whole GeometryNodePath is that it allows the trail to dissipate regardless of if the parent node is removed from the node tree.

**Comment by drewgonzales360** [comment]
Ohh, the trail "reparents" itself in case a bullet or projectile is removed. That way, you can still see it. Having it do it by default would be nice, but just documenting it is was helpful enough for the both of us. It's up to you!

**Comment by tcmug** [comment]
Now an example scene is shipped along with the project :)
