### ISSUE TITLE
Unwanted initial emission point location

### ISSUE THREAD

**Issue by troykinsella** [tcmug/godot_trailmesh#3]
Firstly, this plugin is exactly what I was looking for, so thanks very much for making it!

I am noticing what may be a bug regarding the positioning of the initial emission point of a new `TrailEmitter`. Or, it may be a misconfiguration on my part, but either way, I'd appreciate your input.

My use case is that I have a projectile `RigidBody3D` (an apple), which is the direct parent of a `TrailEmitter`. I want my character (the cylinder) to throw the apple, and show a visual trail of the apple's flight. However, I can't seem to avoid the initial trail point being outside the flight path, as per this screen cap:

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/3dfe7481-1345-4a96-9200-915b36a91ea6)

As soon as my projectile is instanced and added to a parent container node, I am immediately setting its global transform origin. The rigid body is then emitted from the correct "spawn point" and takes the expected flight path. But, as seen, the trail does not start at where the projectile entered the world.

I have tried the following to no avail:
* Setting processing to `false` on the `TrailEmitter` until after the projectile has been instanced, positioned, and forces applied.
* Omitting `TrailEmitter` from the projectile scene, and then only instancing a `PackedScene` of the `TrailEmitter` and adding it as a child of the projectile after forces are applied, etc.
* Initially setting `Update Interval` to 0, and restoring to `0.1` after flight.

Here are some more details about my setup:

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/92fbb75c-9fc6-4df8-ad4c-5742fbe6d531)

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/91c0ed84-c046-4cbe-9e06-8a9732f63e2b)

The MRE of how I'm creating and throwing the projectile is like this:
```
var apple := FRUIT_SCENE.instanciate() # This is the `fruit` RigidBody3D scene as above.
container.add_child(apple)
apple.global_position = <the position of the player's arm>
apple.apply_central_impulse(direction * force)
```

The `fruit.gd` script (attached to the `fruit` RigidBody3D) is not doing anything interesting with the `TrailEmitter` child after that.

Any sense of what I might be doing wrong, here?

I'm using Godot 4.2.1 stable and downloaded this plugin from the AssetLib today.

Thanks.

**Comment by troykinsella** [comment]
Some additional info: I think the rogue first trail point might be related to the camera offset to the emission point, and where the emission point has moved in world space.

In my example, I have the camera afixed to the player, like so:
![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/1538f21e-c0b7-4cc7-8aff-aaaa2330b31f)

When I throw the apple from the player spawn point, there either isn't a rogue first trail point, or it's not visible being perfectly perpendicular to the camera view:

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/b9b1fb8e-2796-47c9-898d-538983c9507e)

But when I move left or right, the first emission point also moves left or right, respectively, becoming visible.

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/44d90159-5e1d-44ef-923e-f486d49db42d)

![image](https://github.com/tcmug/godot_trailmesh/assets/1655907/12d8cdcb-1682-4210-bcac-6afff4a16f34)

**Comment by tcmug** [comment]
Nice find & as commented in the MR I'll give this some thought very soon!

**Comment by DeepDarkDweller** [comment]
is this fix in the latest build? Has this issue been resolved?

**Comment by tcmug** [comment]
It should be.

But in case it's not - I'm working on some code and build pipeline changes which will eventually provide a version which should be fixed.

I'll close this issue for now.
