### ISSUE TITLE
Update Interval var ignored

### ISSUE THREAD

**Issue by ynot01** [tcmug/godot_trailmesh#5]
Godot Engine v4.2.2.rc3.official.16a8334b8

"Update Interval" (update_interval) variable is ignored when set from the editor, but when set at runtime functions normally

Maybe due to https://github.com/tcmug/godot_trailmesh/blob/main/src/trailmesh.cpp#L86

**Comment by tcmug** [comment]
Can you test the latest [version 0.5](https://github.com/tcmug/godot_trailmesh/releases/tag/v0.5)?

**Comment by tcmug** [comment]
Closing, I couldn't replicate.
